name: CI-CD

on: [push, pull_request]

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  release:
    # Only run if the quality check succeeded
    needs: quality

    # IMPORTANT: this permission is mandatory for trusted publishing
    permissions:
      id-token: write
      contents: write

    # Only if this is a push to main without a tag. The tag being pushed will create a new workflow trigger.
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'

    uses: ./.github/workflows/release.yml
    secrets: inherit      

  deploy:
    # Only run if the release action succeeded
    needs: release

    # This enables the upload to Pypi
    permissions:
      id-token: write

    uses: ./.github/workflows/deploy.yml
    if: needs.release.outputs.released == 'true'