name: Release

on: 
  workflow_call: 
    outputs:
      released:
        description: Boolean if the version was incremented and needs to be deployed. 
        value: ${{ jobs.release.outputs.released }}

  workflow_dispatch:

jobs:
  release:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define environment
    environment: release

    # IMPORTANT: this permission is mandatory for trusted publishing
    permissions:
      id-token: write
      contents: write

    # Only if this is a push to main.
    if: github.event.ref == 'refs/heads/main'

    outputs:
      released: ${{steps.released.outputs.released}}

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: released
        uses: python-semantic-release/python-semantic-release@v8.0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install package dependencies
        id: build
        run: poetry build
        # Always rebuild and republish
        # if: steps.released.outputs.released == 'true'

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Test install from TestPyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            sparse-file
        if: steps.released.outputs.released == 'true'

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.released.outputs.released == 'true'
